# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa31dbdb00c4cc5ba6f9d7c62f0c2255481e8d87cb28a615b5ae07b156d921f196ae91afdc0d3aa2ec2c16d63fc427878543b46d366ff8743379363fef371ba

test:
  secret_key_base: 3e1ccedf39484ed8ea23be4fd4e93ea021cd40cde61c1c35bb9eaf8bc615338bac53928a4996e0adf3a4763a6205148ce815deb8a0c1c2c7b02909cece847125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
